//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by StereoDownmixer.rc
//
#define VERSION_RES_MINOR_VER           0
#define VERSION_RES_BUILD               0
#define VER_DEBUG                       0
#define VERSION_RES_MAJOR_VER           1
#define IDS_TITLE                       1
#define IDS_TITLE_PROPERTY_PAGE1        1
#define IDS_TITLE_PROPERTY_PAGE2        2
#define IDS_TITLE_PROPERTY_PAGE3        3
#define IDD_PROPERTIES                  101
#define IDD_PROPERTIES_PAGE1            101
#define IDD_PROPERTIES_PAGE2            102
#define IDD_PROPERTIES_PAGE3            103
#define IDC_PARAMETERS1                 1001
#define IDC_PARAMETERS2                 1002
#define IDC_RADIO_8BITS                 1003
#define IDC_RADIO_16BITS                1004
#define IDC_RADIO_24BITS                1005
#define IDC_RADIO_32BITS                1006
#define IDC_RADIO_SPK_MONO              1007
#define IDC_RADIO_SPK_STEREO            1008
#define IDC_RADIO_SPK_MULTICHANNEL      1009
#define IDC_CHECK_SPK_FL_FR             1011
#define IDC_CHECK_SPK_FC                1012
#define IDC_CHECK_SPK_RL_RR             1013
#define IDC_CHECK_SPK_BL_BR             1013
#define IDC_CHECK_SPK_FLC_FRC           1014
#define IDC_CHECK_SPK_LF                1015
#define IDC_EDIT_VOLUME_GAIN_PERCENT    1016
#define IDC_SLIDER_VOLUME_GAIN_PERCENT  1017
#define IDC_RADIO_DO_NOT_ALTER_VOLUME   1018
#define IDC_RADIO_ALTER_VOLUME          1019
#define IDC_EDIT_REQUIRE_INPUT_SAMPLERATE 1020
#define IDC_RADIO_ALLOW_ANY_INPUT_SAMPLERATE 1021
#define IDC_RADIO_REQUIRE_INPUT_SAMPLERATE 1022
#define IDC_RADIO_ALLOW_ANY_INPUT_NUMBER_OF_CHANNELS 1023
#define IDC_RADIO_REQUIRE_NUMBER_OF_INPUT_CHANNELS 1024
#define IDC_EDIT_REQUIRE_NUMBER_OF_INPUT_CHANNELS 1025
#define IDC_RADIO_ALLOW_ANY_INPUT_BIT_DEPTH 1026
#define IDC_RADIO_REQUIRE_1_BYTE        1027
#define IDC_RADIO_REQUIRE_2_BYTES       1028
#define IDC_RADIO_REQUIRE_3_BYTES       1029
#define IDC_RADIO_REQUIRE_4_BYTES       1030
#define IDC_EDIT_CURRENT_INPUT          1031
#define IDC_EDIT_CURRENT_OUTPUT         1032
#define VERSION_RES_LANGUAGE            0x409
#define IDC_CHECK_RAISE_FILTER_MERIT    1033
#define IDC_CHECK_ENABLE_INPUT_GAINS    1034
#define IDC_SLIDER_I_FL                 1035
#define IDC_SLIDER_I_FR                 1036
#define IDC_SLIDER_I_FC                 1037
#define IDC_SLIDER_I_LF                 1038
#define IDC_SLIDER_I_BL                 1039
#define IDC_SLIDER_I_BR                 1040
#define IDC_SLIDER_I_FLC                1041
#define IDC_SLIDER_I_FRC                1042
#define IDC_SLIDER_I_BC                 1043
#define IDC_SLIDER_I_SL                 1044
#define IDC_SLIDER_I_SR                 1045
#define IDC_SLIDER_I_TC                 1046
#define IDC_SLIDER_I_TFL                1047
#define IDC_SLIDER_I_TFR                1048
#define IDC_SLIDER_I_TFC                1049
#define IDC_SLIDER_I_TBL                1050
#define IDC_SLIDER_I_TBR                1051
#define IDC_SLIDER_I_TBC                1052
#define IDC_CHECK_ENABLE_OUTPUT_GAINS   1053
#define IDC_SLIDER_O_FL                 1054
#define IDC_SLIDER_O_FR                 1055
#define IDC_SLIDER_O_FC                 1056
#define IDC_SLIDER_O_LF                 1057
#define IDC_SLIDER_O_BL                 1058
#define IDC_SLIDER_O_BR                 1059
#define IDC_SLIDER_O_FLC                1060
#define IDC_SLIDER_O_FRC                1061
#define IDC_SLIDER_O_BC                 1062
#define IDC_SLIDER_O_SL                 1063
#define IDC_SLIDER_O_SR                 1064
#define IDC_SLIDER_O_TC                 1065
#define IDC_SLIDER_O_TFL                1066
#define IDC_SLIDER_O_TFR                1067
#define IDC_SLIDER_O_TFC                1068
#define IDC_SLIDER_O_TBL                1069
#define IDC_SLIDER_O_TBR                1070
#define IDC_SLIDER_O_TBC                1071
#define IDC_STATIC_FRAME_OUTPUT_GAINS   1072
#define IDC_STATIC_FRAME_INPUT_GAINS    1073
#define IDC_EDIT_O_FL                   1074
#define IDC_CHECK_JOIN_O_FLFR           1075
#define IDC_STATIC_I_FL                 1076
#define IDC_STATIC_I_FR                 1077
#define IDC_STATIC_I_FC                 1078
#define IDC_STATIC_I_LF                 1079
#define IDC_STATIC_I_BL                 1080
#define IDC_STATIC_I_BR                 1081
#define IDC_STATIC_I_FLC                1082
#define IDC_STATIC_I_FRC                1083
#define IDC_STATIC_I_BC                 1084
#define IDC_STATIC_I_SL                 1085
#define IDC_STATIC_I_SR                 1086
#define IDC_STATIC_I_TC                 1087
#define IDC_STATIC_I_TFL                1088
#define IDC_STATIC_I_TFR                1089
#define IDC_STATIC_I_TFC                1090
#define IDC_STATIC_I_TBL                1091
#define IDC_STATIC_I_TBR                1092
#define IDC_STATIC_I_TBC                1093
#define IDC_STATIC_O_FL                 1094
#define IDC_STATIC_O_FR                 1095
#define IDC_EDIT_O_FR                   1096
#define IDC_EDIT_O_FC                   1097
#define IDC_EDIT_O_LF                   1098
#define IDC_EDIT_O_BL                   1099
#define IDC_EDIT_O_BR                   1100
#define IDC_EDIT_O_FLC                  1101
#define IDC_EDIT_O_FRC                  1102
#define IDC_EDIT_O_BC                   1103
#define IDC_EDIT_O_SL                   1104
#define IDC_EDIT_O_SR                   1105
#define IDC_EDIT_O_TC                   1106
#define IDC_EDIT_O_TFL                  1107
#define IDC_EDIT_O_TFR                  1108
#define IDC_EDIT_O_TFC                  1109
#define IDC_EDIT_O_TBL                  1110
#define IDC_EDIT_O_TBR                  1111
#define IDC_EDIT_O_TBC                  1112
#define IDC_CHECK_JOIN_O_BLBR           1113
#define IDC_CHECK_JOIN_O_FLCFRC         1114
#define IDC_CHECK_JOIN_O_SLSR           1115
#define IDC_CHECK_JOIN_O_TFLTFR         1116
#define IDC_CHECK_JOIN_O_TBLTBR         1117
#define IDC_EDIT_I_FL                   1118
#define IDC_EDIT_I_FR                   1119
#define IDC_EDIT_I_FC                   1120
#define IDC_EDIT_I_LF                   1121
#define IDC_EDIT_I_BL                   1122
#define IDC_EDIT_I_BR                   1123
#define IDC_EDIT_I_FLC                  1124
#define IDC_EDIT_I_FRC                  1125
#define IDC_EDIT_I_BC                   1126
#define IDC_CHECK_JOIN_I_FLFR           1127
#define IDC_CHECK_JOIN_I_BLBR           1128
#define IDC_CHECK_JOIN_I_FLCFRC         1129
#define IDC_EDIT_I_SL                   1130
#define IDC_EDIT_I_SR                   1131
#define IDC_EDIT_I_TC                   1132
#define IDC_EDIT_I_TFL                  1133
#define IDC_EDIT_I_TFR                  1134
#define IDC_EDIT_I_TFC                  1135
#define IDC_EDIT_I_TBL                  1136
#define IDC_EDIT_I_TBR                  1137
#define IDC_EDIT_I_TBC                  1138
#define IDC_CHECK_JOIN_I_SLSR           1139
#define IDC_CHECK_JOIN_I_TFLTFR         1140
#define IDC_CHECK_JOIN_I_TBLTBR         1141
#define IDC_STATIC_O_FC                 1142
#define IDC_STATIC_O_LF                 1143
#define IDC_STATIC_O_BL                 1144
#define IDC_STATIC_O_BR                 1145
#define IDC_STATIC_O_FLC                1146
#define IDC_STATIC_O_FRC                1147
#define IDC_STATIC_O_BC                 1148
#define IDC_STATIC_O_SL                 1149
#define IDC_STATIC_O_SR                 1150
#define IDC_STATIC_O_TC                 1151
#define IDC_STATIC_O_TFL                1152
#define IDC_STATIC_O_TFR                1153
#define IDC_STATIC_O_TFC                1154
#define IDC_STATIC_O_TBL                1155
#define IDC_STATIC_O_TBR                1156
#define IDC_STATIC_O_TBC                1157
#define IDC_SLIDER_MASTER_VOLUME        1158
#define IDC_CHECK_ENABLE_MASTER_VOLUME  1159
#define IDC_EDIT_MASTER_VOLUME          1160
#define IDC_RADIO_USE_INTERNAL_MATRIX   1162
#define IDC_RADIO_USE_CUSTOM_MATRIX     1163
#define IDC_EDIT_CUSTOM_MATRIX_FULL_FILENAME 1164
#define IDC_BUTTON_BROWSE               1165
#define IDC_BUTTON_O_EN_FL              1167
#define IDC_BUTTON_RELOAD_MATRIX_NOW    1168
#define IDC_CHECK_SPK_BC                1169
#define IDC_CHECK_SPK_SL_SR             1170
#define IDC_CHECK_SPK_TC                1171
#define IDC_CHECK_SPK_TFL_TFR           1172
#define IDC_CHECK_SPK_TFC               1173
#define IDC_CHECK_SPK_TBC               1174
#define IDC_CHECK_SPK_TBL_TBR           1175
#define IDC_STATIC_BOTTOM_NOTICE_1      1176
#define IDC_STATIC_BOTTOM_NOTICE_2      1177
#define IDC_BUTTON_O_EN_FR              1201
#define IDC_BUTTON_O_EN_FC              1202
#define IDC_BUTTON_O_EN_LF              1203
#define IDC_BUTTON_O_EN_BL              1204
#define IDC_BUTTON_O_EN_BR              1205
#define IDC_BUTTON_O_EN_FLC             1206
#define IDC_BUTTON_O_EN_FRC             1207
#define IDC_BUTTON_O_EN_SL              1208
#define IDC_BUTTON_O_EN_SR              1209
#define IDC_BUTTON_O_EN_BC              1210
#define IDC_BUTTON_O_EN_TC              1211
#define IDC_BUTTON_O_EN_TFL             1212
#define IDC_BUTTON_O_EN_TFR             1213
#define IDC_BUTTON_O_EN_TFC             1214
#define IDC_BUTTON_O_EN_TBL             1215
#define IDC_BUTTON_O_EN_TBR             1216
#define IDC_BUTTON_O_EN_TBC             1217
#define IDC_BUTTON_I_EN_FL              1218
#define IDC_BUTTON_I_EN_FR              1219
#define IDC_BUTTON_I_EN_FC              1220
#define IDC_BUTTON_I_EN_LF              1221
#define IDC_BUTTON_I_EN_BL              1222
#define IDC_BUTTON_I_EN_BR              1223
#define IDC_BUTTON_I_EN_FLC             1224
#define IDC_BUTTON_I_EN_FRC             1225
#define IDC_BUTTON_I_EN_SL              1226
#define IDC_BUTTON_I_EN_SR              1227
#define IDC_BUTTON_I_EN_BC              1228
#define IDC_BUTTON_I_EN_TC              1229
#define IDC_BUTTON_I_EN_TFL             1230
#define IDC_BUTTON_I_EN_TFR             1231
#define IDC_BUTTON_I_EN_TFC             1232
#define IDC_BUTTON_I_EN_TBL             1233
#define IDC_BUTTON_I_EN_TBR             1234
#define IDC_BUTTON_I_EN_TBC             1235
#define VERSION_RES_CHARSET             1252
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1178
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
